name: Build standard oracle

# {1}
on:
  push:
    branches: [ "master" ]
    paths:
      - 'databases/standard/oracle/**'

jobs:
  build_standard_oracle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: standard-oracle-${{ steps.branch_name.outputs.SOURCE_TAG }}
          path: databases/standard/oracle
