name: Build standard oracle

# {1}
on:
  push:
    branches: [ "master" ]
    paths:
      - 'standard/oracle/**'

jobs:
  build_standard_oracle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: standard-oracle
          path: standard/oracle
