name: Build standard postgres

# {1}
on:
  push:
    branches: [ "main" ]
    paths:
      - standard/postgres/**

jobs:
  build_standard_postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: standard-postgres
          path: standard/postgres
