name: Get tag name


on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  get_tag_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Use tag
        run: echo ${{steps.get_tag_name.outputs.VERSION}}
