name: PR Actions

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  pr-actions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SENSABOT_PAT_TOKEN }}


      - name: Remove feature branch
        run: |
          current_branch=${{ github.head_ref || github.ref_name }}
          if [[ $current_branch != "master" ]]; then
            git push origin --delete $current_branch
          fi
          echo "Branch $current_branch has been deleted"
